### PR TITLE
feat: add more info about failed tests

### PR DESCRIPTION
**Pull request by pernambucano**
### What does this PR do?

It adds more information about failed testes.

### Proof of work

This is an example of what the output will be:

image

### CODE REVIEW

**Comment by pernambucano** [comment]
I'm ok with formatting the info in whatever format is ok for you, I do, however, need to know what happened in the failed tests to jumpstart my debug sessions. 😄

**Review by ryalb — APPROVED** [review]

**Comment by pernambucano** [comment]
One possible change in the format of the failed test  is to remove the first part from it `not ok 1 Chrome 90.0 - [71 ms] -`.

**Comment by pernambucano** [comment]
but this could also be worked on another pr too.

**Comment by pernambucano** [comment]
image

**Pull request merged**
